"use client";
import { useEffect, useRef, useState } from "react";
import { useWorkflowStore, type NodeData } from "@/lib/store";
import { newShot, type Shot } from "@/lib/production";
import { productionAI, parseProductionJSON, generateProductionImage, outputToCanvas } from "@/lib/productionClient";
import { resolveInputs } from "@/lib/executor";
import { MODELS } from "@/lib/models";
import { IMAGE_MODELS, VIDEO_MODELS } from "@/lib/modelConfig";
import { uploadAssetFetch } from "@/lib/media/uploadAssetFetch";
interface Asset { id: string; kind: string; name: string; description: string; imageUrl?: string }
export default function ScriptStudio({ id, data, connectedPrompt }: { id: string; data: NodeData; connectedPrompt?: string }) {
  const update = useWorkflowStore(s => s.updateNodeData), nodes = useWorkflowStore(s => s.nodes), edges = useWorkflowStore(s => s.edges);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [expanded, setExpanded] = useState(false);
  const controller = useRef<AbortController | null>(null);
  const assets = (data.scriptAssets as Asset[] | undefined) ?? [], shots = (data.shots as Shot[] | undefined) ?? [];
  const references = [...resolveInputs(id, nodes, edges).imageUrls, ...((data.scriptReferences as string[] | undefined) ?? [])];
  const patch = (values: Partial<NodeData>) => { useWorkflowStore.getState().pushUndoSnapshot(); update(id, values); };
  async function act(fn: (signal: AbortSignal) => Promise<void>) { if (busy) return; setBusy(true); setError(""); controller.current = new AbortController(); update(id, { status: "running" }); try { await fn(controller.current.signal); update(id, { status: "done" }); } catch (e) { const message = e instanceof Error ? e.message : "Falha no roteiro"; setError(message); update(id, { status: "error", errorMsg: message }); } finally { setBusy(false); } }
  useEffect(() => () => controller.current?.abort(), []);
  async function generate(signal: AbortSignal) {
    const story = connectedPrompt || data.prompt; if (!story) throw new Error("Escreva uma história ou conecte um texto.");
    const reply = await productionAI(`Transforme a história em roteiro técnico audiovisual. Retorne apenas JSON array de até 30 planos {duration:segundos,scene,size,lighting,dialogue,sfx,movement,finalPrompt}. Strings em português. duration entre 1 e 60. Contexto de assets: ${JSON.stringify(assets)}. História: ${story}`, String(data.model ?? "claude-sonnet-4-6"), signal, references);
    const result = parseProductionJSON<Partial<Shot>[]>(reply);
    if (!Array.isArray(result) || !result.length || result.length > 30 || result.some(s => typeof s.scene !== "string" || !Number.isFinite(s.duration) || Number(s.duration) < 1 || Number(s.duration) > 60)) throw new Error("O roteiro retornado tem planos inválidos. A versão atual foi preservada.");
    const next = result.map(s => ({ ...newShot(), duration: Number(s.duration), ...Object.fromEntries(["scene", "size", "lighting", "dialogue", "sfx", "movement", "finalPrompt"].filter(k => typeof s[k as keyof Shot] === "string").map(k => [k, s[k as keyof Shot]])) }));
    patch({ shots: [...shots, ...next] });
  }
  const run = useRef(generate); run.current = generate;
  useEffect(() => { if (data.pendingGenerate && !busy) { update(id, { pendingGenerate: false }); void act(signal => run.current(signal)); } }, [data.pendingGenerate]); // eslint-disable-line react-hooks/exhaustive-deps
  return <>
    <div className="pn-grid"><label>Modelo de roteiro<select value={String(data.model ?? "claude-sonnet-4-6")} onChange={e => update(id, { model: e.target.value })}>{MODELS.map(m => <option key={m.id} value={m.id}>{m.label}</option>)}</select></label><button onClick={() => { setExpanded(!expanded); useWorkflowStore.getState().updateNodeSize(id, expanded ? 760 : 1120, expanded ? 600 : 850); }}>{expanded ? "Recolher roteiro" : "Ampliar roteiro"}</button></div>
    <div className="pn-actions"><button disabled={busy} onClick={() => void act(generate)}>Gerar planos com IA</button><button disabled={busy || !shots.length} onClick={() => void act(async signal => { const reply = await productionAI(`Componha prompts de imagem/vídeo para estes planos mantendo a identidade dos assets. Retorne apenas JSON array de strings, uma por plano, mesma ordem. Assets: ${JSON.stringify(assets)}. Planos: ${JSON.stringify(shots)}`, String(data.model ?? "claude-sonnet-4-6"), signal, references); const prompts = parseProductionJSON<string[]>(reply); if (!Array.isArray(prompts) || prompts.length !== shots.length || prompts.some(p => typeof p !== "string" || !p.trim())) throw new Error("Prompts incompletos. Nenhum plano foi alterado."); patch({ shots: shots.map((s, i) => ({ ...s, finalPrompt: prompts[i] })) }); })}>Sintetizar prompts com IA</button></div>
    <label>Referências de imagem<input type="file" accept="image/*" multiple disabled={busy} onChange={e => { const files = Array.from(e.target.files ?? []); e.target.value = ""; void act(async signal => { const urls = [...references]; for (const file of files.slice(0, Math.max(0, 12 - urls.length))) { const r = await uploadAssetFetch({ method: "POST", headers: { "Content-Type": file.type }, body: file, signal }); const res = await r.json(); if (!r.ok) throw new Error(res.error); urls.push(res.cdnUrl); } patch({ scriptReferences: urls }); }); }} /></label>
    <details><summary>Assets do roteiro · {assets.length}</summary><button disabled={busy || !(data.prompt || connectedPrompt)} onClick={() => void act(async signal => { const reply = await productionAI(`Extraia personagens, cenários e objetos recorrentes. Retorne apenas JSON array de até 20 itens {kind:"Personagem"|"Cenário"|"Objeto",name,description}. História: ${connectedPrompt || data.prompt}. Planos: ${JSON.stringify(shots)}`, String(data.model ?? "claude-sonnet-4-6"), signal, references); const list = parseProductionJSON<Partial<Asset>[]>(reply); if (!Array.isArray(list) || list.length > 20 || list.some(a => !a.name || !a.description)) throw new Error("Inventário inválido."); patch({ scriptAssets: [...assets, ...list.map(a => ({ id: crypto.randomUUID(), kind: String(a.kind || "Objeto"), name: String(a.name), description: String(a.description) }))] }); })}>Preparar assets com IA</button>
    {assets.map(a => <div key={a.id} className="pn-clip"><strong>{a.kind} · {a.name}</strong><textarea aria-label={`Descrição ${a.name}`} value={a.description} onChange={e => update(id, { scriptAssets: assets.map(v => v.id === a.id ? { ...v, description: e.target.value } : v) })} />{a.imageUrl && <img src={a.imageUrl} alt={a.name} style={{ width: 120, borderRadius: 8 }} />}<div className="pn-actions"><button disabled={busy} onClick={() => void act(async signal => { const url = await generateProductionImage(`Ficha de referência consistente de ${a.kind}: ${a.name}. ${a.description}. Fundo simples, sem texto, múltiplos ângulos coerentes.`, references, String(data.batchImageModel ?? "nano-banana-pro"), signal); patch({ scriptAssets: assets.map(v => v.id === a.id ? { ...v, imageUrl: url } : v) }); outputToCanvas(id, url, "image", a.name); })}>{a.imageUrl ? "Gerar nova referência" : "Gerar referência"}</button><button disabled={busy} onClick={() => patch({ scriptAssets: assets.filter(v => v.id !== a.id) })}>Remover</button></div></div>)}
    </details><div className="pn-grid"><label>Modelo dos storyboards<select value={String(data.batchImageModel ?? "nano-banana-pro")} onChange={e => update(id, { batchImageModel: e.target.value })}>{IMAGE_MODELS.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Modelo dos vídeos<select value={String(data.batchVideoModel ?? "kling-3.0")} onChange={e => update(id, { batchVideoModel: e.target.value })}>{VIDEO_MODELS.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div>
    {busy && <p role="status">Trabalhando no roteiro…</p>}{error && <p role="alert" className="pn-error">{error}</p>}
  </>;
}
