"use client";
import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ReactFlow, Background, Controls, type Node, type NodeProps } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { useWorkflowStore, type Space, type NodeData } from "@/lib/store";
import { productionText } from "@/lib/production";
function SharedNode({ data }: NodeProps<Node<NodeData>>) { return <article style={{ width: 280, background: "white", color: "#302343", border: "1px solid #d8cde7", borderRadius: 12, padding: 16 }}><strong>{data.label}</strong>{typeof (data.r2Url || data.imageUrl) === "string" && <img alt={data.label} src={String(data.r2Url || data.imageUrl)} style={{ width: "100%" }} />}{data.videoUrl && <video src={data.videoUrl} controls style={{ width: "100%" }} />}{typeof data.audioUrl === "string" && <audio src={data.audioUrl} controls style={{ width: "100%" }} />}<p style={{ whiteSpace: "pre-wrap", maxHeight: 260, overflow: "auto" }}>{productionText(data) || String(data.outputText || "")}</p></article>; }
const nodeTypes = { shared: SharedNode };
export default function SharedWorkflow({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params), [space, setSpace] = useState<Space | null>(null), [error, setError] = useState(""); const router = useRouter();
  useEffect(() => { let active = true; async function refresh() { try { const res = await fetch(`/api/production/share?token=${encodeURIComponent(token)}`); const body = await res.json(); if (!res.ok) throw new Error(body.error); if (active) { setSpace(body.space); setError(""); } } catch (e) { if (active) setError(String(e)); } } void refresh(); const timer = setInterval(refresh, 10000); return () => { active = false; clearInterval(timer); }; }, [token]);
  return <main style={{ width: "100%", height: "100vh", background: "#f6f3fa" }}><header style={{ padding: 16, display: "flex", gap: 20 }}><strong>{space?.name || "Workflow compartilhado"}</strong><span>Somente leitura · acompanha as alterações do projeto</span><button disabled={!space} onClick={() => { if (!space) return; useWorkflowStore.getState().createSpace(`${space.name} · cópia`, { nodes: structuredClone(space.nodes), edges: structuredClone(space.edges), nodeCounters: space.nodeCounters }); router.push(`/workflow/${useWorkflowStore.getState().activeSpaceId}`); }}>Copiar para meu canvas</button></header>{error ? <p role="alert">{error}</p> : space && <div style={{ height: "calc(100vh - 70px)" }}><ReactFlow nodes={space.nodes.filter(n => n.type !== "groupNode").map(n => { const parent = space.nodes.find(p => p.id === n.parentId); return { ...n, type: "shared", parentId: undefined, position: { x: n.position.x + (parent?.position.x ?? 0), y: n.position.y + (parent?.position.y ?? 0) }, style: { width: 280 }, draggable: false, connectable: false }; })} edges={[]} nodeTypes={nodeTypes} nodesDraggable={false} nodesConnectable={false} elementsSelectable={false} fitView><Background /><Controls showInteractive={false} /></ReactFlow></div>}</main>;
}
